import AntDesign from 'react-native-vector-icons/AntDesign';
import Entypo from 'react-native-vector-icons/Entypo';
import EvilIcons from 'react-native-vector-icons/EvilIcons';
import Feather from 'react-native-vector-icons/Feather';
import FontAwesome from 'react-native-vector-icons/FontAwesome';
import FontAwesome5_Brands from 'react-native-vector-icons/FontAwesome5';
import FontAwesome5_Regular from 'react-native-vector-icons/FontAwesome5';
import FontAwesome5_Solid from 'react-native-vector-icons/FontAwesome5';
import FontAwesome6_Brands from 'react-native-vector-icons/FontAwesome6';
import FontAwesome6_Regular from 'react-native-vector-icons/FontAwesome6';
import FontAwesome6_Solid from 'react-native-vector-icons/FontAwesome6';
import Foundation from 'react-native-vector-icons/Foundation';
import Ionicons from 'react-native-vector-icons/Ionicons';
import MaterialIcons from 'react-native-vector-icons/MaterialIcons';
import MaterialCommunityIcons from 'react-native-vector-icons/MaterialCommunityIcons';
import SimpleLineIcons from 'react-native-vector-icons/SimpleLineIcons';
import Octicons from 'react-native-vector-icons/Octicons';
import Zocial from 'react-native-vector-icons/Zocial';
import Fontisto from 'react-native-vector-icons/Fontisto';

export const AntDesignIcon = AntDesign;
export const EntypoIcon = Entypo;
export const EvilIcon = EvilIcons;
export const FeatherIcon = Feather;
export const FontAwesomeIcon = FontAwesome;
export const FontAwesome5Brands = FontAwesome5_Brands;
export const FontAwesome5Regular = FontAwesome5_Regular;
export const FontAwesome5Solid = FontAwesome5_Solid;
export const FontAwesome6Brands = FontAwesome6_Brands;
export const FontAwesome6Regular = FontAwesome6_Regular;
export const FontAwesome6Solid = FontAwesome6_Solid;
export const FoundationIcon = Foundation;
export const IonIcon = Ionicons;
export const MaterialIcon = MaterialIcons;
export const MaterialCommunity = MaterialCommunityIcons;
export const SimpleLineIcon = SimpleLineIcons;
export const Octicon = Octicons;
export const ZocialIcon = Zocial;
export const FontistoIcon = Fontisto;
